version: '3.1'

services:

  wordpress:
    image: wordpress:php7.3
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: app
      WORDPRESS_DB_USER: app
      WORDPRESS_DB_PASSWORD: app@secret

  wordpress-cli:
    image: wordpress:cli-php7.3

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app@secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
