version: '3.1'

services:

  mysql:
    build: docker/mysql
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app@secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net

  wordpress:
    build: docker/wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: app
      WORDPRESS_DB_USER: app
      WORDPRESS_DB_PASSWORD: app@secret
    volumes:
      - wordpress_html:/var/www/html
    networks:
      - net

volumes:
  mysql_data:
  wordpress_html:

networks:
  net:
